"""
KrishiMitra Comprehensive Crop Database v2.0
150+ Indian crops with full agronomic, economic and climate profiles.

Fields per crop:
  name_hindi, name_local  – localised names
  season                  – rabi | kharif | zaid | year_round
  category                – Cereal | Pulse | Oilseed | Vegetable | Fruit |
                            Spice | Cash | Fiber | Plantation | Medicinal | Millet
  soil_preference         – list of suitable soil types
  water_requirement       – Low | Moderate | High | Very High
  temperature_min/max     – °C range
  rainfall_mm             – annual mm needed
  duration_days           – harvest period
  yield_per_hectare       – quintals
  msp_per_quintal         – ₹ (0 = no MSP)
  profit_per_hectare      – realistic net profit ₹
  input_cost_per_hectare  – ₹
  export_potential        – Low | Medium | High | Very High
  market_demand           – Low | Medium | High | Very High
  volatility              – Low | Medium | High | Very High
  government_support      – text label
  agro_zones              – list of zones where this thrives
  states_primary          – list of states where this is a major crop
"""

from typing import Dict, Any, List

# Agro-climatic zone definitions
ZONES = {
    "himalayan":    ["Himachal Pradesh", "Uttarakhand", "Jammu and Kashmir", "Ladakh", "Sikkim", "Arunachal Pradesh"],
    "indo_gangetic": ["Punjab", "Haryana", "Uttar Pradesh", "Bihar", "West Bengal"],
    "thar_desert":  ["Rajasthan"],
    "peninsular":   ["Maharashtra", "Karnataka", "Andhra Pradesh", "Telangana", "Tamil Nadu"],
    "coastal":      ["Kerala", "Goa", "Odisha", "West Bengal"],
    "central":      ["Madhya Pradesh", "Chhattisgarh"],
    "northeast":    ["Assam", "Meghalaya", "Manipur", "Mizoram", "Nagaland", "Tripura", "Arunachal Pradesh"],
    "northwest":    ["Punjab", "Haryana", "Delhi", "Rajasthan"],
    "gujarat":      ["Gujarat"],
    "deccan":       ["Maharashtra", "Karnataka", "Telangana"],
}

def _crop(
    *,
    name_hindi: str,
    season: str,
    category: str,
    soils: List[str],
    water: str,
    temp_min: float,
    temp_max: float,
    rainfall_mm: int,
    days: int,
    yield_q: float,
    msp: int,
    input_cost: int,
    profit: int,
    export: str = "Low",
    demand: str = "Medium",
    volatility: str = "Medium",
    support: str = "MSP",
    agro_zones: List[str] = None,
    states: List[str] = None,
    name_local: Dict[str, str] = None,
) -> Dict[str, Any]:
    return {
        "name_hindi": name_hindi,
        "name_local": name_local or {},
        "season": season,
        "category": category,
        "soil_preference": soils,
        "water_requirement": water,
        "temperature_min": temp_min,
        "temperature_max": temp_max,
        "rainfall_mm": rainfall_mm,
        "duration_days": days,
        "yield_per_hectare": yield_q,
        "msp_per_quintal": msp,
        "input_cost_per_hectare": input_cost,
        "profit_per_hectare": profit,
        "export_potential": export,
        "market_demand": demand,
        "volatility": volatility,
        "government_support": support,
        "agro_zones": agro_zones or [],
        "states_primary": states or [],
    }


# Shorthand soil lists
LOAMY    = ["Alluvial", "Loamy", "Sandy Loam"]
ALLUVIAL = ["Alluvial", "Loamy"]
BLACK    = ["Black", "Vertisol", "Clay Loam"]
RED      = ["Red", "Laterite", "Sandy Loam"]
SANDY    = ["Sandy", "Sandy Loam"]
SANDY_LOAM = ["Sandy Loam", "Loamy"]
CLAY     = ["Clay", "Clay Loam", "Alluvial"]
ALL_SOILS = ["Alluvial", "Loamy", "Sandy Loam", "Black", "Red", "Laterite"]

ALL_CROP_DATA: Dict[str, Dict[str, Any]] = {

    # ═══════════════════════════════════════════════
    # CEREALS
    # ═══════════════════════════════════════════════
    "wheat": _crop(
        name_hindi="गेहूँ", season="rabi", category="Cereal",
        soils=ALLUVIAL + ["Sandy Loam", "Clay Loam"],
        water="Moderate", temp_min=10, temp_max=25, rainfall_mm=450,
        days=120, yield_q=45, msp=2275, input_cost=25000, profit=77375,
        export="High", demand="Very High", volatility="Low", support="High MSP",
        agro_zones=["indo_gangetic","northwest","central","himalayan"],
        states=["Punjab","Haryana","Uttar Pradesh","Madhya Pradesh","Rajasthan","Bihar"],
        name_local={"pa":"ਕਣਕ","bn":"গম","te":"గోధుమ","mr":"गहू","ta":"கோதுமை","gu":"ઘઉં","kn":"ಗೋಧಿ","ml":"ഗോതമ്പ്","or":"ଗହମ","as":"ঘেঁহু","ur":"گندم"},
    ),
    "rice": _crop(
        name_hindi="धान", season="kharif", category="Cereal",
        soils=CLAY + ["Alluvial"],
        water="High", temp_min=20, temp_max=35, rainfall_mm=1200,
        days=150, yield_q=40, msp=2300, input_cost=30000, profit=62000,
        export="High", demand="Very High", volatility="Medium", support="High MSP",
        agro_zones=["indo_gangetic","coastal","northeast","peninsular"],
        states=["West Bengal","Uttar Pradesh","Punjab","Andhra Pradesh","Tamil Nadu","Odisha","Assam","Bihar"],
        name_local={"pa":"ਝੋਨਾ","bn":"ধান","te":"వరి","mr":"भात","ta":"நெல்","gu":"ડાંગર","kn":"ಭತ್ತ","ml":"നെല്ല്","or":"ଧାନ","as":"ধান","ur":"چاول"},
    ),
    "maize": _crop(
        name_hindi="मक्का", season="kharif", category="Cereal",
        soils=LOAMY + ["Sandy Loam"],
        water="Moderate", temp_min=18, temp_max=32, rainfall_mm=600,
        days=100, yield_q=35, msp=2090, input_cost=22000, profit=51150,
        export="High", demand="High", volatility="Medium", support="MSP",
        agro_zones=["indo_gangetic","peninsular","central","northwest"],
        states=["Karnataka","Andhra Pradesh","Telangana","Bihar","Uttar Pradesh","Maharashtra","Rajasthan"],
        name_local={"pa":"ਮੱਕੀ","bn":"ভুট্টা","te":"మొక్కజొన్న","mr":"मका","ta":"சோளம்","gu":"મકાઈ","kn":"ಮೆಕ್ಕೆ","ml":"ചോളം","or":"ମକା","as":"ভুট্টা"},
    ),
    "barley": _crop(
        name_hindi="जौ", season="rabi", category="Cereal",
        soils=SANDY_LOAM + ["Alluvial"],
        water="Low", temp_min=7, temp_max=20, rainfall_mm=300,
        days=100, yield_q=30, msp=1735, input_cost=15000, profit=37050,
        export="Medium", demand="Medium", volatility="Low", support="MSP",
        agro_zones=["northwest","indo_gangetic","thar_desert"],
        states=["Uttar Pradesh","Rajasthan","Madhya Pradesh","Haryana"],
        name_local={"pa":"ਜੌਂ","bn":"যব","te":"బార్లీ","mr":"सातू","ta":"வாற்கோதுமை","gu":"જવ","kn":"ಬಾರ್ಲಿ","or":"ଯବ"},
    ),
    "bajra": _crop(
        name_hindi="बाजरा", season="kharif", category="Millet",
        soils=SANDY + ["Sandy Loam"],
        water="Low", temp_min=25, temp_max=40, rainfall_mm=250,
        days=80, yield_q=20, msp=2625, input_cost=8000, profit=44500,
        export="Low", demand="Medium", volatility="Low", support="MSP",
        agro_zones=["thar_desert","northwest","peninsular"],
        states=["Rajasthan","Gujarat","Haryana","Uttar Pradesh","Maharashtra"],
        name_local={"pa":"ਬਾਜਰਾ","bn":"বাজরা","te":"సజ్జ","mr":"बाजरी","ta":"கம்பு","gu":"બાજરી","kn":"ಸಜ್ಜೆ","ml":"കമ്പ്","or":"ବାଜରା"},
    ),
    "jowar": _crop(
        name_hindi="ज्वार", season="kharif", category="Millet",
        soils=LOAMY + BLACK,
        water="Low", temp_min=20, temp_max=38, rainfall_mm=400,
        days=100, yield_q=20, msp=3371, input_cost=12000, profit=55420,
        export="Low", demand="Medium", volatility="Low", support="MSP",
        agro_zones=["deccan","peninsular","central"],
        states=["Maharashtra","Karnataka","Andhra Pradesh","Telangana","Madhya Pradesh"],
        name_local={"mr":"ज्वारी","te":"జొన్న","ta":"சோளம்","kn":"ಜೋಳ","gu":"જુવાર","or":"ଜୁଆର"},
    ),
    "ragi": _crop(
        name_hindi="रागी", season="kharif", category="Millet",
        soils=RED + ["Sandy Loam","Laterite"],
        water="Moderate", temp_min=18, temp_max=32, rainfall_mm=700,
        days=90, yield_q=15, msp=3846, input_cost=10000, profit=47690,
        export="Medium", demand="High", volatility="Low", support="MSP",
        agro_zones=["peninsular","deccan","himalayan"],
        states=["Karnataka","Andhra Pradesh","Telangana","Tamil Nadu","Uttarakhand","Odisha"],
        name_local={"kn":"ರಾಗಿ","te":"రాగి","ta":"கேழ்வரகு","ml":"കുതിര","or":"ମଣ୍ଡିଆ"},
    ),
    "sorghum": _crop(
        name_hindi="शर्बत ज्वार", season="rabi", category="Millet",
        soils=LOAMY + BLACK,
        water="Low", temp_min=15, temp_max=35, rainfall_mm=400,
        days=110, yield_q=22, msp=3371, input_cost=14000, profit=60162,
        export="Low", demand="Medium", volatility="Low", support="MSP",
        agro_zones=["deccan","peninsular","central"],
        states=["Maharashtra","Karnataka","Madhya Pradesh"],
    ),
    "basmati_rice": _crop(
        name_hindi="बासमती", season="kharif", category="Cereal",
        soils=ALLUVIAL,
        water="High", temp_min=20, temp_max=35, rainfall_mm=1200,
        days=140, yield_q=35, msp=3500, input_cost=55000, profit=67500,
        export="Very High", demand="Very High", volatility="Medium", support="High MSP",
        agro_zones=["indo_gangetic","himalayan"],
        states=["Punjab","Haryana","Uttar Pradesh","Uttarakhand","Himachal Pradesh"],
    ),
    "foxtail_millet": _crop(
        name_hindi="कंगनी", season="kharif", category="Millet",
        soils=SANDY_LOAM,
        water="Low", temp_min=20, temp_max=35, rainfall_mm=500,
        days=70, yield_q=15, msp=2500, input_cost=8000, profit=29500,
        export="Low", demand="Medium", volatility="Low", support="MSP",
        agro_zones=["peninsular","thar_desert"],
        states=["Andhra Pradesh","Telangana","Rajasthan"],
    ),

    # ═══════════════════════════════════════════════
    # PULSES
    # ═══════════════════════════════════════════════
    "gram": _crop(
        name_hindi="चना", season="rabi", category="Pulse",
        soils=LOAMY + ["Sandy Loam","Clay Loam"],
        water="Low", temp_min=15, temp_max=25, rainfall_mm=400,
        days=120, yield_q=15, msp=5440, input_cost=18000, profit=63600,
        export="High", demand="High", volatility="Low", support="High MSP",
        agro_zones=["central","indo_gangetic","northwest","deccan"],
        states=["Madhya Pradesh","Rajasthan","Maharashtra","Uttar Pradesh","Karnataka","Andhra Pradesh"],
        name_local={"pa":"ਛੋਲੇ","bn":"ছোলা","te":"శనగ","mr":"हरभरा","ta":"கொண்டைக்கடலை","gu":"ચણા","kn":"ಕಡಲೆ","ml":"കടല","or":"ଚଣା","ur":"چنا"},
    ),
    "tur": _crop(
        name_hindi="अरहर/तुअर", season="kharif", category="Pulse",
        soils=LOAMY + RED,
        water="Moderate", temp_min=20, temp_max=30, rainfall_mm=600,
        days=150, yield_q=12, msp=7000, input_cost=20000, profit=64000,
        export="High", demand="High", volatility="Medium", support="High MSP",
        agro_zones=["peninsular","deccan","central","indo_gangetic"],
        states=["Maharashtra","Karnataka","Uttar Pradesh","Madhya Pradesh","Andhra Pradesh","Gujarat"],
        name_local={"mr":"तूर","te":"కంది","ta":"தொகுப்பு","kn":"ತೊಗರಿ","ml":"തുവര","gu":"તુવેર","or":"ହରଡ"},
    ),
    "moong": _crop(
        name_hindi="मूंग", season="kharif", category="Pulse",
        soils=LOAMY + SANDY_LOAM,
        water="Low", temp_min=20, temp_max=32, rainfall_mm=400,
        days=80, yield_q=10, msp=8682, input_cost=14000, profit=72820,
        export="High", demand="High", volatility="Medium", support="High MSP",
        agro_zones=["indo_gangetic","central","peninsular"],
        states=["Rajasthan","Maharashtra","Andhra Pradesh","Karnataka","Bihar"],
        name_local={"pa":"ਮੂੰਗੀ","bn":"মুগ","te":"పెసలు","mr":"मूग","ta":"பயறு","gu":"મગ","kn":"ಹೆಸರು","ml":"ചെറുപയർ","or":"ମୁଗ"},
    ),
    "urad": _crop(
        name_hindi="उड़द", season="kharif", category="Pulse",
        soils=LOAMY + CLAY,
        water="Moderate", temp_min=20, temp_max=35, rainfall_mm=600,
        days=90, yield_q=10, msp=6950, input_cost=16000, profit=53500,
        export="High", demand="High", volatility="Medium", support="High MSP",
        agro_zones=["indo_gangetic","peninsular","central"],
        states=["Uttar Pradesh","Madhya Pradesh","Andhra Pradesh","Tamil Nadu","Rajasthan"],
        name_local={"pa":"ਮਾਂਹ","bn":"মসুর","te":"మినుములు","mr":"उडीद","ta":"உளுந்து","gu":"અળદ","kn":"ಉದ್ದು","ml":"ഉഴുന്ന്","or":"ବିରି"},
    ),
    "masoor": _crop(
        name_hindi="मसूर", season="rabi", category="Pulse",
        soils=LOAMY + ALLUVIAL,
        water="Low", temp_min=10, temp_max=25, rainfall_mm=350,
        days=100, yield_q=12, msp=6425, input_cost=15000, profit=62100,
        export="High", demand="High", volatility="Low", support="High MSP",
        agro_zones=["indo_gangetic","central"],
        states=["Madhya Pradesh","Uttar Pradesh","Bihar","West Bengal"],
        name_local={"bn":"মসুর","te":"మసూరి","mr":"मसूर","ta":"முசுர்","gu":"મસૂર","kn":"ಮಸೂರ","or":"ମସୁର"},
    ),
    "matar": _crop(
        name_hindi="मटर", season="rabi", category="Pulse",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=10, temp_max=20, rainfall_mm=400,
        days=90, yield_q=20, msp=5400, input_cost=20000, profit=88000,
        export="Medium", demand="High", volatility="Medium", support="MSP",
        agro_zones=["himalayan","indo_gangetic","northwest"],
        states=["Uttar Pradesh","Madhya Pradesh","Punjab","Himachal Pradesh","Uttarakhand"],
        name_local={"pa":"ਮਟਰ","bn":"মটর","te":"బఠానీ","mr":"वाटाणा","ta":"பட்டாணி","gu":"વટાણા","kn":"ಬಟಾಣಿ"},
    ),
    "lobia": _crop(
        name_hindi="लोबिया", season="kharif", category="Pulse",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=20, temp_max=32, rainfall_mm=600,
        days=90, yield_q=15, msp=5400, input_cost=18000, profit=63000,
        export="Medium", demand="High", volatility="Medium", support="MSP",
        agro_zones=["indo_gangetic","peninsular"],
        states=["Karnataka","Andhra Pradesh","Tamil Nadu","Maharashtra"],
    ),
    "rajma": _crop(
        name_hindi="राजमा", season="rabi", category="Pulse",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=8, temp_max=22, rainfall_mm=500,
        days=120, yield_q=15, msp=5400, input_cost=20000, profit=61000,
        export="Medium", demand="High", volatility="Low", support="MSP",
        agro_zones=["himalayan","indo_gangetic"],
        states=["Uttarakhand","Himachal Pradesh","Jammu and Kashmir","Uttar Pradesh"],
    ),
    "groundnut": _crop(
        name_hindi="मूंगफली", season="kharif", category="Oilseed",
        soils=SANDY_LOAM + ["Sandy"],
        water="Moderate", temp_min=20, temp_max=32, rainfall_mm=500,
        days=120, yield_q=25, msp=6783, input_cost=25000, profit=144575,
        export="High", demand="High", volatility="Medium", support="MSP",
        agro_zones=["gujarat","peninsular","thar_desert"],
        states=["Gujarat","Andhra Pradesh","Tamil Nadu","Karnataka","Rajasthan","Maharashtra"],
        name_local={"gu":"મગફળી","te":"వేరుశనగ","ta":"வேர்க்கடலை","kn":"ಕಡಲೆ","ml":"കപ്പലണ്ടി","mr":"भुईमूग","pa":"ਮੂੰਗਫਲੀ","or":"ଚିନাବାଦାମ"},
    ),

    # ═══════════════════════════════════════════════
    # OILSEEDS
    # ═══════════════════════════════════════════════
    "mustard": _crop(
        name_hindi="सरसों", season="rabi", category="Oilseed",
        soils=LOAMY + SANDY_LOAM,
        water="Low", temp_min=10, temp_max=25, rainfall_mm=350,
        days=120, yield_q=20, msp=5650, input_cost=20000, profit=93000,
        export="Medium", demand="High", volatility="Medium", support="MSP",
        agro_zones=["northwest","indo_gangetic","thar_desert"],
        states=["Rajasthan","Uttar Pradesh","Haryana","Madhya Pradesh","West Bengal","Gujarat"],
        name_local={"pa":"ਸਰ੍ਹੋਂ","bn":"সরিষা","te":"ఆవాలు","mr":"मोहरी","ta":"கடுகு","gu":"સરસવ","kn":"ಸಾಸಿವೆ","ml":"കടുക്","or":"ସୋରିଷ"},
    ),
    "soybean": _crop(
        name_hindi="सोयाबीन", season="kharif", category="Oilseed",
        soils=BLACK + LOAMY,
        water="Moderate", temp_min=20, temp_max=30, rainfall_mm=700,
        days=100, yield_q=20, msp=4892, input_cost=20000, profit=77840,
        export="High", demand="High", volatility="Medium", support="MSP",
        agro_zones=["central","deccan"],
        states=["Madhya Pradesh","Maharashtra","Rajasthan","Chhattisgarh","Karnataka"],
        name_local={"mr":"सोयाबीन","te":"సోయాబీన్","gu":"સોયાબીન","kn":"ಸೋಯಾಬೀನ್","or":"ସୋୟାବିନ"},
    ),
    "sunflower": _crop(
        name_hindi="सूरजमुखी", season="rabi", category="Oilseed",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=15, temp_max=28, rainfall_mm=500,
        days=100, yield_q=15, msp=7280, input_cost=18000, profit=91200,
        export="Medium", demand="Medium", volatility="Medium", support="MSP",
        agro_zones=["peninsular","deccan","indo_gangetic"],
        states=["Karnataka","Andhra Pradesh","Maharashtra","Uttar Pradesh","Haryana","Tamil Nadu"],
        name_local={"kn":"ಸೂರ್ಯಕಾಂತಿ","te":"పొద్దుతిరుగుడు","mr":"सूर्यफूल","ta":"சூரியகாந்தி"},
    ),
    "sesame": _crop(
        name_hindi="तिल", season="kharif", category="Oilseed",
        soils=SANDY_LOAM + LOAMY,
        water="Low", temp_min=22, temp_max=38, rainfall_mm=400,
        days=90, yield_q=8, msp=9267, input_cost=15000, profit=59136,
        export="High", demand="Medium", volatility="High", support="MSP",
        agro_zones=["peninsular","central","coastal"],
        states=["Gujarat","Rajasthan","West Bengal","Madhya Pradesh","Tamil Nadu","Uttar Pradesh"],
        name_local={"gu":"તલ","te":"నువ్వులు","mr":"तीळ","ta":"எள்","kn":"ಎಳ್ಳು","ml":"എള്ള്","or":"ତିଳ"},
    ),
    "linseed": _crop(
        name_hindi="अलसी", season="rabi", category="Oilseed",
        soils=LOAMY + CLAY,
        water="Low", temp_min=10, temp_max=22, rainfall_mm=350,
        days=120, yield_q=10, msp=6240, input_cost=15000, profit=47400,
        export="Medium", demand="Low", volatility="Medium", support="MSP",
        agro_zones=["central","indo_gangetic"],
        states=["Madhya Pradesh","Uttar Pradesh","Bihar","Odisha","Maharashtra"],
    ),
    "castor": _crop(
        name_hindi="अरंडी", season="kharif", category="Oilseed",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=20, temp_max=38, rainfall_mm=500,
        days=150, yield_q=12, msp=6620, input_cost=18000, profit=61440,
        export="High", demand="Medium", volatility="Medium", support="MSP",
        agro_zones=["gujarat","peninsular","thar_desert"],
        states=["Gujarat","Rajasthan","Andhra Pradesh","Karnataka","Odisha"],
        name_local={"gu":"દિવેળ","te":"ఆముదం","kn":"ಹರಳು"},
    ),
    "cotton": _crop(
        name_hindi="कपास", season="kharif", category="Fiber",
        soils=BLACK + ["Clay Loam","Alluvial"],
        water="Moderate", temp_min=20, temp_max=38, rainfall_mm=600,
        days=180, yield_q=15, msp=7121, input_cost=45000, profit=61815,
        export="Very High", demand="High", volatility="Medium", support="MSP",
        agro_zones=["deccan","gujarat","peninsular","northwest"],
        states=["Maharashtra","Gujarat","Telangana","Andhra Pradesh","Karnataka","Rajasthan","Punjab","Haryana","Madhya Pradesh"],
        name_local={"mr":"कापूस","te":"పత్తి","gu":"કપાસ","kn":"ಹತ್ತಿ","ml":"പരുത்തി","ta":"பருத்தி","pa":"ਕਪਾਹ","or":"କପା"},
    ),

    # ═══════════════════════════════════════════════
    # CASH CROPS
    # ═══════════════════════════════════════════════
    "sugarcane": _crop(
        name_hindi="गन्ना", season="year_round", category="Cash",
        soils=ALLUVIAL + LOAMY,
        water="High", temp_min=25, temp_max=38, rainfall_mm=1500,
        days=365, yield_q=700, msp=340, input_cost=80000, profit=158000,
        export="Medium", demand="High", volatility="Low", support="High MSP",
        agro_zones=["indo_gangetic","peninsular","coastal"],
        states=["Uttar Pradesh","Maharashtra","Karnataka","Tamil Nadu","Gujarat","Andhra Pradesh","Haryana","Punjab"],
        name_local={"pa":"ਗੰਨਾ","bn":"আখ","te":"చెరకు","mr":"ऊस","ta":"கரும்பு","gu":"શેરડી","kn":"ಕಬ್ಬು","ml":"കരിമ്പ്","or":"ଆଖୁ","ur":"گنا"},
    ),
    "jute": _crop(
        name_hindi="जूट", season="kharif", category="Fiber",
        soils=ALLUVIAL + CLAY,
        water="High", temp_min=22, temp_max=38, rainfall_mm=1200,
        days=120, yield_q=200, msp=5050, input_cost=40000, profit=61000,
        export="High", demand="Medium", volatility="Medium", support="MSP",
        agro_zones=["indo_gangetic","northeast","coastal"],
        states=["West Bengal","Bihar","Assam","Odisha"],
        name_local={"bn":"পাট","or":"ଜୁଟ","as":"পাট"},
    ),
    "tobacco": _crop(
        name_hindi="तंबाकू", season="kharif", category="Cash",
        soils=SANDY_LOAM + LOAMY,
        water="Moderate", temp_min=18, temp_max=32, rainfall_mm=600,
        days=120, yield_q=30, msp=0, input_cost=80000, profit=100000,
        export="High", demand="Medium", volatility="High", support="Low",
        agro_zones=["peninsular","coastal"],
        states=["Andhra Pradesh","Karnataka","Gujarat","Uttar Pradesh","West Bengal","Bihar"],
    ),
    "tea": _crop(
        name_hindi="चाय", season="year_round", category="Plantation",
        soils=["Acidic", "Laterite", "Loamy"],
        water="High", temp_min=15, temp_max=28, rainfall_mm=2000,
        days=365, yield_q=50, msp=0, input_cost=200000, profit=250000,
        export="Very High", demand="High", volatility="Medium", support="Tea Board",
        agro_zones=["northeast","himalayan"],
        states=["Assam","West Bengal","Kerala","Tamil Nadu","Karnataka"],
    ),
    "coffee": _crop(
        name_hindi="कॉफी", season="year_round", category="Plantation",
        soils=["Laterite","Red","Loamy"],
        water="Moderate", temp_min=15, temp_max=28, rainfall_mm=1500,
        days=365, yield_q=30, msp=0, input_cost=150000, profit=180000,
        export="Very High", demand="High", volatility="High", support="Coffee Board",
        agro_zones=["peninsular","himalayan"],
        states=["Karnataka","Kerala","Tamil Nadu"],
    ),
    "rubber": _crop(
        name_hindi="रबर", season="year_round", category="Plantation",
        soils=["Laterite","Red","Sandy Loam"],
        water="High", temp_min=22, temp_max=34, rainfall_mm=2000,
        days=365, yield_q=20, msp=0, input_cost=100000, profit=150000,
        export="High", demand="High", volatility="Medium", support="Rubber Board",
        agro_zones=["coastal","peninsular"],
        states=["Kerala","Karnataka","Tamil Nadu","Andhra Pradesh","Assam"],
    ),
    "coconut": _crop(
        name_hindi="नारियल", season="year_round", category="Plantation",
        soils=["Sandy","Sandy Loam","Laterite"],
        water="High", temp_min=22, temp_max=35, rainfall_mm=1500,
        days=365, yield_q=100, msp=0, input_cost=80000, profit=150000,
        export="High", demand="High", volatility="Low", support="Coconut Development Board",
        agro_zones=["coastal","peninsular"],
        states=["Kerala","Tamil Nadu","Karnataka","Andhra Pradesh","Odisha","West Bengal"],
        name_local={"ml":"തേങ്ങ","ta":"தேங்காய்","kn":"ತೆಂಗು","te":"కొబ్బరి","or":"ନଡ଼ିଆ"},
    ),

    # ═══════════════════════════════════════════════
    # VEGETABLES
    # ═══════════════════════════════════════════════
    "potato": _crop(
        name_hindi="आलू", season="rabi", category="Vegetable",
        soils=SANDY_LOAM + LOAMY,
        water="Moderate", temp_min=10, temp_max=25, rainfall_mm=500,
        days=90, yield_q=200, msp=0, input_cost=80000, profit=40000,
        export="Medium", demand="Very High", volatility="High", support="Cold Storage",
        agro_zones=["indo_gangetic","himalayan","northwest"],
        states=["Uttar Pradesh","West Bengal","Bihar","Gujarat","Punjab","Madhya Pradesh","Assam"],
        name_local={"pa":"ਆਲੂ","bn":"আলু","te":"బంగాళాదుంప","mr":"बटाटा","ta":"உருளைக்கிழங்கு","gu":"બટાટા","kn":"ಆಲೂಗಡ್ಡೆ","ml":"ഉരുളക്കിഴങ്ങ്","or":"ଆଳୁ"},
    ),
    "onion": _crop(
        name_hindi="प्याज", season="rabi", category="Vegetable",
        soils=SANDY_LOAM + LOAMY,
        water="Moderate", temp_min=12, temp_max=28, rainfall_mm=700,
        days=120, yield_q=150, msp=0, input_cost=60000, profit=240000,
        export="High", demand="Very High", volatility="Very High", support="Storage subsidy",
        agro_zones=["deccan","peninsular","central"],
        states=["Maharashtra","Madhya Pradesh","Karnataka","Gujarat","Rajasthan","Andhra Pradesh","Uttar Pradesh"],
        name_local={"pa":"ਪਿਆਜ਼","bn":"পেঁয়াজ","te":"ఉల్లి","mr":"कांदा","ta":"வெங்காயம்","gu":"ડુંગળી","kn":"ಈರುಳ್ಳಿ","ml":"സവോള","or":"ପିଆଜ"},
    ),
    "tomato": _crop(
        name_hindi="टमाटर", season="year_round", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=18, temp_max=32, rainfall_mm=600,
        days=90, yield_q=300, msp=0, input_cost=120000, profit=120000,
        export="High", demand="Very High", volatility="High", support="Greenhouse",
        agro_zones=["peninsular","indo_gangetic","himalayan"],
        states=["Andhra Pradesh","Karnataka","Maharashtra","Odisha","Tamil Nadu","Uttar Pradesh","Gujarat"],
        name_local={"pa":"ਟਮਾਟਰ","bn":"টমেটো","te":"టమాటా","mr":"टोमॅटो","ta":"தக்காளி","gu":"ટામેટા","kn":"ಟೊಮೆಟೊ","ml":"തക്കാളി","or":"ଟମାଟୋ"},
    ),
    "brinjal": _crop(
        name_hindi="बैंगन", season="year_round", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=18, temp_max=35, rainfall_mm=700,
        days=120, yield_q=200, msp=0, input_cost=80000, profit=120000,
        export="Low", demand="High", volatility="Medium", support="Low",
        agro_zones=["peninsular","indo_gangetic"],
        states=["West Bengal","Odisha","Karnataka","Gujarat","Bihar","Andhra Pradesh"],
    ),
    "okra": _crop(
        name_hindi="भिंडी", season="kharif", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=22, temp_max=38, rainfall_mm=600,
        days=90, yield_q=150, msp=0, input_cost=60000, profit=90000,
        export="Low", demand="High", volatility="Medium", support="Low",
        agro_zones=["peninsular","indo_gangetic","central"],
        states=["Gujarat","West Bengal","Uttar Pradesh","Andhra Pradesh","Bihar"],
    ),
    "cauliflower": _crop(
        name_hindi="फूलगोभी", season="rabi", category="Vegetable",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=12, temp_max=22, rainfall_mm=500,
        days=90, yield_q=200, msp=0, input_cost=70000, profit=130000,
        export="Low", demand="High", volatility="Medium", support="Low",
        agro_zones=["indo_gangetic","himalayan","northwest"],
        states=["Uttar Pradesh","Bihar","West Bengal","Haryana","Maharashtra"],
    ),
    "cabbage": _crop(
        name_hindi="पत्तागोभी", season="rabi", category="Vegetable",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=10, temp_max=22, rainfall_mm=500,
        days=90, yield_q=250, msp=0, input_cost=60000, profit=125000,
        export="Low", demand="High", volatility="Medium", support="Low",
        agro_zones=["himalayan","indo_gangetic","northwest"],
        states=["Uttar Pradesh","West Bengal","Odisha","Maharashtra","Assam"],
    ),
    "capsicum": _crop(
        name_hindi="शिमला मिर्च", season="year_round", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=18, temp_max=28, rainfall_mm=600,
        days=120, yield_q=150, msp=0, input_cost=80000, profit=150000,
        export="Medium", demand="High", volatility="High", support="Greenhouse",
        agro_zones=["himalayan","peninsular"],
        states=["Himachal Pradesh","Karnataka","Andhra Pradesh","Uttarakhand"],
    ),
    "chilli": _crop(
        name_hindi="मिर्च", season="year_round", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=20, temp_max=35, rainfall_mm=600,
        days=120, yield_q=100, msp=0, input_cost=60000, profit=200000,
        export="High", demand="Very High", volatility="Very High", support="Spice Board",
        agro_zones=["peninsular","deccan","central"],
        states=["Andhra Pradesh","Telangana","Maharashtra","Karnataka","Odisha","West Bengal","Rajasthan"],
        name_local={"te":"మిరపకాయలు","mr":"मिरची","ta":"மிளகாய்","kn":"ಮೆಣಸಿನಕಾಯಿ","ml":"മുളക്","or":"ଲଙ୍କା","gu":"મરચું"},
    ),
    "ginger": _crop(
        name_hindi="अदरक", season="kharif", category="Spice",
        soils=LOAMY + ["Sandy Loam","Red"],
        water="Moderate", temp_min=20, temp_max=32, rainfall_mm=1500,
        days=200, yield_q=150, msp=0, input_cost=100000, profit=200000,
        export="High", demand="High", volatility="High", support="Spice Board",
        agro_zones=["coastal","peninsular","northeast","himalayan"],
        states=["Kerala","Karnataka","Assam","Meghalaya","Andhra Pradesh","Himachal Pradesh"],
        name_local={"ml":"ഇഞ്ചി","kn":"ಶುಂಠಿ","te":"అల్లం","ta":"இஞ்சி","or":"ଅଦା","as":"আদা"},
    ),
    "turmeric": _crop(
        name_hindi="हल्दी", season="kharif", category="Spice",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=20, temp_max=35, rainfall_mm=1200,
        days=200, yield_q=25, msp=6000, input_cost=80000, profit=70000,
        export="Very High", demand="High", volatility="Medium", support="Spice Board",
        agro_zones=["peninsular","deccan","coastal","northeast"],
        states=["Andhra Pradesh","Telangana","Karnataka","Tamil Nadu","Odisha","Maharashtra","West Bengal"],
        name_local={"te":"పసుపు","ta":"மஞ்சள்","kn":"ಅರಿಶಿನ","ml":"മഞ്ഞൾ","mr":"हळद","or":"ହଳଦି","as":"হালধি","bn":"হলুদ"},
    ),
    "garlic": _crop(
        name_hindi="लहसुन", season="rabi", category="Spice",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=12, temp_max=24, rainfall_mm=500,
        days=120, yield_q=80, msp=0, input_cost=60000, profit=120000,
        export="Medium", demand="High", volatility="High", support="Low",
        agro_zones=["central","northwest","peninsular"],
        states=["Madhya Pradesh","Gujarat","Rajasthan","Uttar Pradesh","Maharashtra","Andhra Pradesh"],
        name_local={"gu":"લસણ","mr":"लसूण","te":"వెల్లుల్లి","ta":"பூண்டு","kn":"ಬೆಳ್ಳುಳ್ಳಿ","ml":"വെള്ളുള്ളി","pa":"ਲਸਣ","bn":"রসুন"},
    ),
    "coriander": _crop(
        name_hindi="धनिया", season="rabi", category="Spice",
        soils=SANDY_LOAM + LOAMY,
        water="Low", temp_min=12, temp_max=26, rainfall_mm=400,
        days=90, yield_q=12, msp=6450, input_cost=20000, profit=57400,
        export="High", demand="High", volatility="Medium", support="MSP",
        agro_zones=["thar_desert","central","indo_gangetic"],
        states=["Rajasthan","Madhya Pradesh","Gujarat","Andhra Pradesh","Uttar Pradesh"],
    ),
    "cumin": _crop(
        name_hindi="जीरा", season="rabi", category="Spice",
        soils=SANDY_LOAM + SANDY,
        water="Low", temp_min=8, temp_max=22, rainfall_mm=250,
        days=120, yield_q=8, msp=0, input_cost=25000, profit=95000,
        export="High", demand="High", volatility="High", support="Spice Board",
        agro_zones=["thar_desert","gujarat"],
        states=["Gujarat","Rajasthan"],
        name_local={"gu":"જીરું","ta":"சீரகம்","kn":"ಜೀರಿಗೆ","te":"జీలకర్ర","ml":"ജീരകം"},
    ),
    "cardamom": _crop(
        name_hindi="इलायची", season="year_round", category="Spice",
        soils=["Loamy","Laterite","Forest Loam"],
        water="High", temp_min=15, temp_max=25, rainfall_mm=2500,
        days=365, yield_q=3, msp=0, input_cost=150000, profit=350000,
        export="Very High", demand="High", volatility="High", support="Spice Board",
        agro_zones=["coastal","peninsular","himalayan"],
        states=["Kerala","Tamil Nadu","Karnataka","Sikkim","Arunachal Pradesh"],
        name_local={"ml":"ഏലം","ta":"ஏலக்காய்","kn":"ಏಲಕ್ಕಿ","te":"ఏలకులు"},
    ),
    "black_pepper": _crop(
        name_hindi="काली मिर्च", season="year_round", category="Spice",
        soils=["Laterite","Red","Loamy"],
        water="High", temp_min=20, temp_max=32, rainfall_mm=2000,
        days=365, yield_q=5, msp=0, input_cost=80000, profit=220000,
        export="Very High", demand="High", volatility="High", support="Spice Board",
        agro_zones=["coastal","peninsular"],
        states=["Kerala","Karnataka","Tamil Nadu"],
        name_local={"ml":"കുരുമുളക്","kn":"ಕರಿಮೆಣಸು","te":"మిరియాలు","ta":"கருமிளகு"},
    ),
    "fennel": _crop(
        name_hindi="सौंफ", season="rabi", category="Spice",
        soils=SANDY_LOAM + LOAMY,
        water="Low", temp_min=10, temp_max=22, rainfall_mm=350,
        days=120, yield_q=10, msp=0, input_cost=30000, profit=100000,
        export="High", demand="High", volatility="Medium", support="Spice Board",
        agro_zones=["thar_desert","gujarat"],
        states=["Gujarat","Rajasthan"],
    ),

    # ═══════════════════════════════════════════════
    # FRUITS
    # ═══════════════════════════════════════════════
    "mango": _crop(
        name_hindi="आम", season="year_round", category="Fruit",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=18, temp_max=38, rainfall_mm=750,
        days=365, yield_q=200, msp=3500, input_cost=150000, profit=300000,
        export="Very High", demand="Very High", volatility="Medium", support="NHM",
        agro_zones=["indo_gangetic","peninsular","coastal"],
        states=["Uttar Pradesh","Andhra Pradesh","Karnataka","Maharashtra","Bihar","West Bengal","Gujarat","Tamil Nadu"],
        name_local={"pa":"ਅੰਬ","bn":"আম","te":"మామిడి","mr":"आंबा","ta":"மாம்பழம்","gu":"કેરી","kn":"ಮಾವು","ml":"മാങ്ങ","or":"ଆମ୍ବ","as":"আম"},
    ),
    "banana": _crop(
        name_hindi="केला", season="year_round", category="Fruit",
        soils=LOAMY + ALLUVIAL,
        water="High", temp_min=20, temp_max=38, rainfall_mm=1200,
        days=365, yield_q=400, msp=2200, input_cost=120000, profit=280000,
        export="High", demand="Very High", volatility="Low", support="NHM",
        agro_zones=["peninsular","coastal","indo_gangetic"],
        states=["Andhra Pradesh","Gujarat","Tamil Nadu","Maharashtra","Karnataka","Madhya Pradesh","Assam"],
        name_local={"te":"అరటి","ta":"வாழைப்பழம்","kn":"ಬಾಳೆ","ml":"പഴം","mr":"केळी","gu":"કેળ","or":"କଦଳୀ","as":"কল"},
    ),
    "grapes": _crop(
        name_hindi="अंगूर", season="year_round", category="Fruit",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=15, temp_max=32, rainfall_mm=500,
        days=365, yield_q=200, msp=4500, input_cost=150000, profit=350000,
        export="Very High", demand="High", volatility="High", support="NHM",
        agro_zones=["peninsular","thar_desert","deccan"],
        states=["Maharashtra","Karnataka","Andhra Pradesh","Tamil Nadu","Himachal Pradesh"],
    ),
    "pomegranate": _crop(
        name_hindi="अनार", season="year_round", category="Fruit",
        soils=SANDY_LOAM + LOAMY,
        water="Moderate", temp_min=12, temp_max=38, rainfall_mm=500,
        days=365, yield_q=150, msp=6500, input_cost=120000, profit=300000,
        export="High", demand="High", volatility="Medium", support="NHM",
        agro_zones=["thar_desert","deccan","peninsular"],
        states=["Maharashtra","Gujarat","Rajasthan","Karnataka","Andhra Pradesh"],
    ),
    "papaya": _crop(
        name_hindi="पपीता", season="year_round", category="Fruit",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=20, temp_max=38, rainfall_mm=800,
        days=300, yield_q=300, msp=1800, input_cost=80000, profit=220000,
        export="Medium", demand="High", volatility="Low", support="NHM",
        agro_zones=["peninsular","indo_gangetic","coastal"],
        states=["Andhra Pradesh","Karnataka","Gujarat","West Bengal","Madhya Pradesh"],
    ),
    "guava": _crop(
        name_hindi="अमरूद", season="year_round", category="Fruit",
        soils=ALL_SOILS,
        water="Low", temp_min=15, temp_max=38, rainfall_mm=500,
        days=365, yield_q=200, msp=1500, input_cost=80000, profit=180000,
        export="Medium", demand="High", volatility="Low", support="NHM",
        agro_zones=["peninsular","indo_gangetic","central"],
        states=["Uttar Pradesh","Maharashtra","Bihar","Karnataka","Andhra Pradesh"],
    ),
    "apple": _crop(
        name_hindi="सेब", season="year_round", category="Fruit",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=4, temp_max=20, rainfall_mm=1000,
        days=365, yield_q=120, msp=8000, input_cost=180000, profit=300000,
        export="High", demand="Very High", volatility="Medium", support="NHM",
        agro_zones=["himalayan"],
        states=["Himachal Pradesh","Jammu and Kashmir","Uttarakhand","Arunachal Pradesh"],
        name_local={"pa":"ਸੇਬ","hi":"सेब","ur":"سیب"},
    ),
    "litchi": _crop(
        name_hindi="लीची", season="year_round", category="Fruit",
        soils=LOAMY + SANDY_LOAM,
        water="High", temp_min=15, temp_max=30, rainfall_mm=1200,
        days=365, yield_q=100, msp=5000, input_cost=120000, profit=280000,
        export="High", demand="High", volatility="Medium", support="NHM",
        agro_zones=["indo_gangetic","northeast"],
        states=["Bihar","Jharkhand","West Bengal","Uttar Pradesh","Assam"],
    ),
    "orange": _crop(
        name_hindi="संतरा", season="year_round", category="Fruit",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=14, temp_max=30, rainfall_mm=750,
        days=365, yield_q=150, msp=3200, input_cost=100000, profit=200000,
        export="High", demand="High", volatility="Medium", support="NHM",
        agro_zones=["deccan","himalayan","central"],
        states=["Maharashtra","Madhya Pradesh","Rajasthan","Punjab","Karnataka","Andhra Pradesh"],
    ),
    "watermelon": _crop(
        name_hindi="तरबूज", season="zaid", category="Fruit",
        soils=SANDY_LOAM + SANDY,
        water="Moderate", temp_min=24, temp_max=40, rainfall_mm=400,
        days=90, yield_q=300, msp=0, input_cost=60000, profit=180000,
        export="Low", demand="Very High", volatility="High", support="Low",
        agro_zones=["thar_desert","peninsular","indo_gangetic"],
        states=["Andhra Pradesh","Karnataka","Tamil Nadu","Rajasthan","Uttar Pradesh","Madhya Pradesh"],
    ),
    "muskmelon": _crop(
        name_hindi="खरबूजा", season="zaid", category="Fruit",
        soils=SANDY_LOAM + SANDY,
        water="Moderate", temp_min=24, temp_max=40, rainfall_mm=400,
        days=90, yield_q=250, msp=0, input_cost=50000, profit=150000,
        export="Low", demand="High", volatility="High", support="Low",
        agro_zones=["thar_desert","peninsular"],
        states=["Uttar Pradesh","Rajasthan","Andhra Pradesh","Punjab"],
    ),
    "pineapple": _crop(
        name_hindi="अनानास", season="year_round", category="Fruit",
        soils=["Laterite","Sandy Loam","Red"],
        water="Moderate", temp_min=22, temp_max=35, rainfall_mm=1500,
        days=365, yield_q=200, msp=2500, input_cost=100000, profit=250000,
        export="High", demand="High", volatility="Medium", support="NHM",
        agro_zones=["northeast","coastal","peninsular"],
        states=["Assam","Meghalaya","Manipur","West Bengal","Kerala","Karnataka"],
    ),
    "strawberry": _crop(
        name_hindi="स्ट्रॉबेरी", season="rabi", category="Fruit",
        soils=SANDY_LOAM + LOAMY,
        water="Moderate", temp_min=6, temp_max=22, rainfall_mm=800,
        days=120, yield_q=100, msp=12000, input_cost=150000, profit=350000,
        export="High", demand="Very High", volatility="High", support="NHM",
        agro_zones=["himalayan","peninsular"],
        states=["Himachal Pradesh","Uttarakhand","Maharashtra","Karnataka"],
    ),

    # ═══════════════════════════════════════════════
    # HORTICULTURE / SPICES
    # ═══════════════════════════════════════════════
    "aloe_vera": _crop(
        name_hindi="एलोवेरा", season="year_round", category="Medicinal",
        soils=SANDY + SANDY_LOAM,
        water="Low", temp_min=18, temp_max=40, rainfall_mm=300,
        days=365, yield_q=100, msp=0, input_cost=60000, profit=200000,
        export="High", demand="High", volatility="Low", support="AYUSH",
        agro_zones=["thar_desert","peninsular","gujarat"],
        states=["Rajasthan","Gujarat","Andhra Pradesh","Maharashtra"],
    ),
    "ashwagandha": _crop(
        name_hindi="अश्वगंधा", season="kharif", category="Medicinal",
        soils=SANDY_LOAM + LOAMY,
        water="Low", temp_min=18, temp_max=35, rainfall_mm=600,
        days=150, yield_q=10, msp=0, input_cost=50000, profit=150000,
        export="High", demand="High", volatility="Medium", support="AYUSH",
        agro_zones=["thar_desert","central","peninsular"],
        states=["Rajasthan","Madhya Pradesh","Punjab","Gujarat","Haryana"],
    ),
    "stevia": _crop(
        name_hindi="स्टीविया", season="year_round", category="Medicinal",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=18, temp_max=30, rainfall_mm=700,
        days=365, yield_q=50, msp=0, input_cost=80000, profit=220000,
        export="Very High", demand="Very High", volatility="High", support="AYUSH",
        agro_zones=["peninsular","himalayan"],
        states=["Uttarakhand","Karnataka","Andhra Pradesh","Maharashtra"],
    ),
    "moringa": _crop(
        name_hindi="सहजन", season="year_round", category="Medicinal",
        soils=LOAMY + SANDY_LOAM,
        water="Low", temp_min=20, temp_max=40, rainfall_mm=400,
        days=365, yield_q=120, msp=0, input_cost=50000, profit=200000,
        export="Very High", demand="Very High", volatility="Medium", support="AYUSH",
        agro_zones=["peninsular","central","thar_desert"],
        states=["Tamil Nadu","Andhra Pradesh","Karnataka","Gujarat","Maharashtra"],
    ),
    "lemongrass": _crop(
        name_hindi="नींबू घास", season="year_round", category="Medicinal",
        soils=LOAMY + RED,
        water="Moderate", temp_min=18, temp_max=35, rainfall_mm=800,
        days=365, yield_q=100, msp=0, input_cost=30000, profit=120000,
        export="High", demand="High", volatility="Medium", support="AYUSH",
        agro_zones=["peninsular","northeast","coastal"],
        states=["Assam","Kerala","Karnataka","Tamil Nadu","Maharashtra"],
    ),

    # ═══════════════════════════════════════════════
    # ADDITIONAL VEGETABLES
    # ═══════════════════════════════════════════════
    "carrot": _crop(
        name_hindi="गाजर", season="rabi", category="Vegetable",
        soils=SANDY_LOAM + LOAMY,
        water="Moderate", temp_min=8, temp_max=22, rainfall_mm=450,
        days=100, yield_q=300, msp=0, input_cost=50000, profit=100000,
        export="Low", demand="High", volatility="Low", support="Low",
        agro_zones=["himalayan","northwest","indo_gangetic"],
        states=["Punjab","Haryana","Uttar Pradesh","Himachal Pradesh","Bihar"],
    ),
    "radish": _crop(
        name_hindi="मूली", season="rabi", category="Vegetable",
        soils=SANDY_LOAM + LOAMY,
        water="Moderate", temp_min=10, temp_max=22, rainfall_mm=400,
        days=60, yield_q=200, msp=0, input_cost=30000, profit=70000,
        export="Low", demand="Medium", volatility="Low", support="Low",
        agro_zones=["himalayan","northwest","indo_gangetic"],
        states=["Uttar Pradesh","Bihar","Haryana","Punjab","West Bengal"],
    ),
    "peas": _crop(
        name_hindi="मटर", season="rabi", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=8, temp_max=20, rainfall_mm=450,
        days=90, yield_q=80, msp=0, input_cost=50000, profit=100000,
        export="Low", demand="High", volatility="Medium", support="Low",
        agro_zones=["himalayan","northwest","indo_gangetic"],
        states=["Uttar Pradesh","Madhya Pradesh","Punjab","Himachal Pradesh","Bihar"],
    ),
    "spinach": _crop(
        name_hindi="पालक", season="year_round", category="Vegetable",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=10, temp_max=25, rainfall_mm=500,
        days=30, yield_q=100, msp=0, input_cost=20000, profit=50000,
        export="Low", demand="High", volatility="Low", support="Low",
        agro_zones=["indo_gangetic","himalayan","northwest"],
        states=["Uttar Pradesh","Punjab","Haryana","Maharashtra","Gujarat"],
    ),
    "bitter_gourd": _crop(
        name_hindi="करेला", season="kharif", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=22, temp_max=38, rainfall_mm=600,
        days=120, yield_q=100, msp=0, input_cost=50000, profit=100000,
        export="Low", demand="Medium", volatility="Medium", support="Low",
        agro_zones=["peninsular","indo_gangetic"],
        states=["Maharashtra","Karnataka","Andhra Pradesh","West Bengal","Odisha"],
    ),
    "bottle_gourd": _crop(
        name_hindi="लौकी", season="kharif", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=20, temp_max=38, rainfall_mm=600,
        days=120, yield_q=150, msp=0, input_cost=40000, profit=75000,
        export="Low", demand="High", volatility="Low", support="Low",
        agro_zones=["indo_gangetic","peninsular"],
        states=["Uttar Pradesh","Bihar","West Bengal","Maharashtra"],
    ),
    "mushroom": _crop(
        name_hindi="मशरूम", season="year_round", category="Vegetable",
        soils=["Organic Compost"],
        water="High", temp_min=14, temp_max=28, rainfall_mm=0,
        days=45, yield_q=200, msp=0, input_cost=100000, profit=400000,
        export="High", demand="Very High", volatility="Medium", support="Low",
        agro_zones=["himalayan","indo_gangetic","peninsular"],
        states=["Himachal Pradesh","Uttarakhand","Haryana","Punjab","Maharashtra","Karnataka"],
    ),
    "sweet_potato": _crop(
        name_hindi="शकरकंद", season="kharif", category="Vegetable",
        soils=SANDY_LOAM + LOAMY,
        water="Moderate", temp_min=20, temp_max=32, rainfall_mm=800,
        days=120, yield_q=250, msp=0, input_cost=50000, profit=100000,
        export="Low", demand="Medium", volatility="Low", support="Low",
        agro_zones=["indo_gangetic","peninsular","northeast"],
        states=["Odisha","West Bengal","Uttar Pradesh","Andhra Pradesh","Maharashtra"],
    ),

    # ═══════════════════════════════════════════════
    # PLANTATION / SPECIALTY
    # ═══════════════════════════════════════════════
    "bamboo": _crop(
        name_hindi="बांस", season="year_round", category="Plantation",
        soils=ALL_SOILS,
        water="Moderate", temp_min=14, temp_max=40, rainfall_mm=800,
        days=365, yield_q=300, msp=0, input_cost=50000, profit=150000,
        export="Medium", demand="High", volatility="Low", support="NBMMP",
        agro_zones=["northeast","himalayan","peninsular"],
        states=["Assam","Maharashtra","Odisha","Karnataka","Madhya Pradesh"],
    ),
    "oil_palm": _crop(
        name_hindi="तेल पाम", season="year_round", category="Plantation",
        soils=LOAMY + CLAY,
        water="High", temp_min=24, temp_max=35, rainfall_mm=2000,
        days=365, yield_q=200, msp=0, input_cost=120000, profit=280000,
        export="High", demand="Very High", volatility="Medium", support="NMOOP",
        agro_zones=["coastal","peninsular"],
        states=["Andhra Pradesh","Telangana","Karnataka","Tamil Nadu","Odisha","Mizoram"],
    ),
    "cashew": _crop(
        name_hindi="काजू", season="year_round", category="Plantation",
        soils=["Sandy","Laterite","Red"],
        water="Low", temp_min=20, temp_max=38, rainfall_mm=1000,
        days=365, yield_q=8, msp=0, input_cost=80000, profit=200000,
        export="Very High", demand="High", volatility="Medium", support="Cashew Board",
        agro_zones=["coastal","peninsular"],
        states=["Maharashtra","Goa","Kerala","Karnataka","Tamil Nadu","Andhra Pradesh","Odisha"],
    ),
    "areca_nut": _crop(
        name_hindi="सुपारी", season="year_round", category="Plantation",
        soils=LOAMY + ["Laterite"],
        water="High", temp_min=20, temp_max=35, rainfall_mm=1700,
        days=365, yield_q=50, msp=0, input_cost=100000, profit=250000,
        export="High", demand="High", volatility="Medium", support="Low",
        agro_zones=["coastal","peninsular"],
        states=["Karnataka","Kerala","Assam","West Bengal","Meghalaya"],
    ),

    # ═══════════════════════════════════════════════
    # CEREALS (additional)
    # ═══════════════════════════════════════════════
    "kharif_sorghum": _crop(
        name_hindi="खरीफ ज्वार", season="kharif", category="Cereal",
        soils=LOAMY + BLACK,
        water="Low", temp_min=22, temp_max=40, rainfall_mm=450,
        days=110, yield_q=22, msp=3371, input_cost=13000, profit=61162,
        export="Low", demand="Medium", volatility="Low", support="MSP",
        agro_zones=["peninsular", "deccan", "central"],
        states=["Maharashtra", "Karnataka", "Madhya Pradesh", "Andhra Pradesh", "Telangana"],
    ),
    "triticale": _crop(
        name_hindi="ट्रिटिकेल", season="rabi", category="Cereal",
        soils=SANDY_LOAM + ALLUVIAL,
        water="Low", temp_min=5, temp_max=22, rainfall_mm=350,
        days=120, yield_q=38, msp=0, input_cost=18000, profit=42000,
        export="Low", demand="Low", volatility="Low", support="Limited",
        agro_zones=["himalayan", "northwest", "indo_gangetic"],
        states=["Punjab", "Haryana", "Uttar Pradesh", "Himachal Pradesh"],
    ),
    "oat": _crop(
        name_hindi="जई", season="rabi", category="Cereal",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=5, temp_max=20, rainfall_mm=400,
        days=100, yield_q=25, msp=0, input_cost=12000, profit=28000,
        export="Low", demand="Medium", volatility="Low", support="Limited",
        agro_zones=["northwest", "indo_gangetic", "himalayan"],
        states=["Punjab", "Haryana", "Uttar Pradesh", "Uttarakhand"],
    ),
    "amaranth": _crop(
        name_hindi="राजगिरा", season="kharif", category="Cereal",
        soils=SANDY_LOAM + LOAMY,
        water="Low", temp_min=18, temp_max=35, rainfall_mm=350,
        days=90, yield_q=15, msp=0, input_cost=10000, profit=50000,
        export="Medium", demand="High", volatility="Medium", support="Low",
        agro_zones=["himalayan", "peninsular", "central"],
        states=["Uttar Pradesh", "Maharashtra", "Rajasthan", "Gujarat", "Uttarakhand"],
    ),

    # ═══════════════════════════════════════════════
    # VEGETABLES (additional)
    # ═══════════════════════════════════════════════
    "pumpkin": _crop(
        name_hindi="कद्दू", season="kharif", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=18, temp_max=35, rainfall_mm=600,
        days=80, yield_q=200, msp=0, input_cost=18000, profit=62000,
        export="Low", demand="High", volatility="Medium", support="Low",
        agro_zones=["indo_gangetic", "peninsular", "northeast"],
        states=["Uttar Pradesh", "Madhya Pradesh", "Bihar", "West Bengal", "Odisha"],
    ),
    "ridge_gourd": _crop(
        name_hindi="तोरई", season="kharif", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=20, temp_max=38, rainfall_mm=600,
        days=65, yield_q=120, msp=0, input_cost=15000, profit=45000,
        export="Low", demand="High", volatility="Medium", support="Low",
        agro_zones=["peninsular", "indo_gangetic", "central"],
        states=["Maharashtra", "Gujarat", "Andhra Pradesh", "Karnataka", "Uttar Pradesh"],
    ),
    "snake_gourd": _crop(
        name_hindi="चिचिन्डा", season="kharif", category="Vegetable",
        soils=LOAMY + RED,
        water="Moderate", temp_min=22, temp_max=38, rainfall_mm=650,
        days=70, yield_q=150, msp=0, input_cost=16000, profit=54000,
        export="Low", demand="Medium", volatility="Medium", support="Low",
        agro_zones=["peninsular", "coastal", "northeast"],
        states=["Kerala", "Karnataka", "Tamil Nadu", "Andhra Pradesh", "West Bengal"],
    ),
    "tinda": _crop(
        name_hindi="टिंडा", season="kharif", category="Vegetable",
        soils=SANDY_LOAM + LOAMY,
        water="Moderate", temp_min=25, temp_max=42, rainfall_mm=400,
        days=60, yield_q=100, msp=0, input_cost=12000, profit=38000,
        export="Low", demand="Medium", volatility="High", support="Low",
        agro_zones=["northwest", "thar_desert", "indo_gangetic"],
        states=["Punjab", "Haryana", "Rajasthan", "Uttar Pradesh", "Delhi"],
    ),
    "ivy_gourd": _crop(
        name_hindi="कुंदरू", season="year_round", category="Vegetable",
        soils=LOAMY + RED,
        water="Moderate", temp_min=20, temp_max=38, rainfall_mm=600,
        days=90, yield_q=130, msp=0, input_cost=14000, profit=46000,
        export="Low", demand="Medium", volatility="Medium", support="Low",
        agro_zones=["peninsular", "coastal", "central"],
        states=["Andhra Pradesh", "Tamil Nadu", "Karnataka", "Maharashtra", "Odisha"],
    ),
    "cluster_beans": _crop(
        name_hindi="ग्वार", season="kharif", category="Vegetable",
        soils=SANDY + SANDY_LOAM,
        water="Low", temp_min=25, temp_max=42, rainfall_mm=250,
        days=75, yield_q=8, msp=0, input_cost=8000, profit=32000,
        export="Very High", demand="High", volatility="High", support="Low",
        agro_zones=["thar_desert", "northwest", "gujarat"],
        states=["Rajasthan", "Gujarat", "Haryana", "Punjab"],
    ),
    "drumstick": _crop(
        name_hindi="सहजन", season="year_round", category="Vegetable",
        soils=SANDY_LOAM + RED,
        water="Low", temp_min=22, temp_max=42, rainfall_mm=400,
        days=180, yield_q=40, msp=0, input_cost=15000, profit=80000,
        export="High", demand="High", volatility="Low", support="Low",
        agro_zones=["peninsular", "deccan", "coastal"],
        states=["Tamil Nadu", "Andhra Pradesh", "Karnataka", "Maharashtra", "Kerala"],
    ),
    "beetroot": _crop(
        name_hindi="चुकंदर", season="rabi", category="Vegetable",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=10, temp_max=24, rainfall_mm=450,
        days=70, yield_q=200, msp=0, input_cost=18000, profit=62000,
        export="Low", demand="High", volatility="Medium", support="Low",
        agro_zones=["himalayan", "northwest", "indo_gangetic"],
        states=["Maharashtra", "Punjab", "Haryana", "Gujarat", "Uttar Pradesh"],
    ),
    "sweet_corn": _crop(
        name_hindi="स्वीट कॉर्न", season="kharif", category="Vegetable",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=18, temp_max=32, rainfall_mm=600,
        days=75, yield_q=80, msp=0, input_cost=25000, profit=95000,
        export="Low", demand="Very High", volatility="Medium", support="Low",
        agro_zones=["indo_gangetic", "peninsular", "northwest"],
        states=["Karnataka", "Maharashtra", "Uttar Pradesh", "Punjab", "Haryana"],
    ),
    "baby_corn": _crop(
        name_hindi="बेबी कॉर्न", season="kharif", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=18, temp_max=32, rainfall_mm=550,
        days=60, yield_q=25, msp=0, input_cost=22000, profit=78000,
        export="High", demand="High", volatility="Medium", support="Low",
        agro_zones=["indo_gangetic", "peninsular"],
        states=["Karnataka", "Uttar Pradesh", "Punjab", "Maharashtra", "Haryana"],
    ),
    "kale": _crop(
        name_hindi="काले", season="rabi", category="Vegetable",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=5, temp_max=22, rainfall_mm=450,
        days=60, yield_q=150, msp=0, input_cost=20000, profit=80000,
        export="Medium", demand="High", volatility="Medium", support="Low",
        agro_zones=["himalayan", "northwest", "indo_gangetic"],
        states=["Punjab", "Haryana", "Uttar Pradesh", "Himachal Pradesh", "Maharashtra"],
    ),
    "curry_leaves": _crop(
        name_hindi="करी पत्ता", season="year_round", category="Vegetable",
        soils=RED + LOAMY,
        water="Low", temp_min=20, temp_max=38, rainfall_mm=500,
        days=365, yield_q=30, msp=0, input_cost=20000, profit=120000,
        export="High", demand="Very High", volatility="Low", support="Low",
        agro_zones=["peninsular", "coastal", "deccan"],
        states=["Tamil Nadu", "Karnataka", "Andhra Pradesh", "Maharashtra", "Kerala"],
    ),

    # ═══════════════════════════════════════════════
    # FRUITS (additional)
    # ═══════════════════════════════════════════════
    "amla": _crop(
        name_hindi="आँवला", season="year_round", category="Fruit",
        soils=SANDY_LOAM + RED,
        water="Low", temp_min=15, temp_max=40, rainfall_mm=600,
        days=365, yield_q=60, msp=0, input_cost=40000, profit=160000,
        export="High", demand="Very High", volatility="Low", support="Low",
        agro_zones=["central", "indo_gangetic", "deccan"],
        states=["Uttar Pradesh", "Madhya Pradesh", "Rajasthan", "Gujarat", "Maharashtra"],
    ),
    "jamun": _crop(
        name_hindi="जामुन", season="year_round", category="Fruit",
        soils=ALLUVIAL + LOAMY,
        water="Low", temp_min=15, temp_max=38, rainfall_mm=700,
        days=365, yield_q=50, msp=0, input_cost=30000, profit=120000,
        export="Low", demand="High", volatility="Medium", support="Low",
        agro_zones=["indo_gangetic", "peninsular", "central"],
        states=["Uttar Pradesh", "Maharashtra", "Gujarat", "Madhya Pradesh", "Karnataka"],
    ),
    "custard_apple": _crop(
        name_hindi="सीताफल", season="year_round", category="Fruit",
        soils=RED + SANDY_LOAM,
        water="Low", temp_min=22, temp_max=38, rainfall_mm=500,
        days=365, yield_q=80, msp=0, input_cost=35000, profit=165000,
        export="Medium", demand="High", volatility="Medium", support="Low",
        agro_zones=["deccan", "peninsular", "central"],
        states=["Andhra Pradesh", "Maharashtra", "Karnataka", "Gujarat", "Madhya Pradesh"],
    ),
    "jackfruit": _crop(
        name_hindi="कटहल", season="year_round", category="Fruit",
        soils=ALLUVIAL + LOAMY,
        water="Moderate", temp_min=22, temp_max=38, rainfall_mm=1200,
        days=365, yield_q=100, msp=0, input_cost=30000, profit=140000,
        export="Medium", demand="High", volatility="Low", support="Low",
        agro_zones=["coastal", "peninsular", "northeast"],
        states=["Kerala", "Bihar", "West Bengal", "Assam", "Odisha", "Tamil Nadu"],
    ),
    "sapota": _crop(
        name_hindi="चीकू", season="year_round", category="Fruit",
        soils=SANDY_LOAM + RED,
        water="Moderate", temp_min=22, temp_max=38, rainfall_mm=800,
        days=365, yield_q=100, msp=0, input_cost=50000, profit=200000,
        export="Medium", demand="High", volatility="Medium", support="Low",
        agro_zones=["gujarat", "peninsular", "coastal"],
        states=["Gujarat", "Maharashtra", "Karnataka", "Tamil Nadu", "Andhra Pradesh"],
    ),
    "fig": _crop(
        name_hindi="अंजीर", season="year_round", category="Fruit",
        soils=LOAMY + RED + SANDY_LOAM,
        water="Low", temp_min=15, temp_max=38, rainfall_mm=400,
        days=365, yield_q=25, msp=0, input_cost=50000, profit=250000,
        export="High", demand="High", volatility="Medium", support="Low",
        agro_zones=["peninsular", "gujarat", "thar_desert"],
        states=["Maharashtra", "Gujarat", "Karnataka", "Uttar Pradesh", "Rajasthan"],
    ),
    "date_palm": _crop(
        name_hindi="खजूर", season="year_round", category="Fruit",
        soils=SANDY + SANDY_LOAM,
        water="Low", temp_min=20, temp_max=48, rainfall_mm=150,
        days=365, yield_q=70, msp=0, input_cost=60000, profit=280000,
        export="High", demand="High", volatility="Low", support="Low",
        agro_zones=["thar_desert", "gujarat", "northwest"],
        states=["Rajasthan", "Gujarat", "Punjab", "Haryana"],
    ),
    "mulberry": _crop(
        name_hindi="शहतूत", season="year_round", category="Fruit",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=13, temp_max=38, rainfall_mm=800,
        days=365, yield_q=30, msp=0, input_cost=25000, profit=90000,
        export="Low", demand="Medium", volatility="Low", support="Sericulture Dept",
        agro_zones=["peninsular", "himalayan", "northeast"],
        states=["Karnataka", "West Bengal", "Jammu and Kashmir", "Uttarakhand", "Andhra Pradesh"],
    ),
    "avocado": _crop(
        name_hindi="एवोकाडो", season="year_round", category="Fruit",
        soils=LOAMY + RED,
        water="Moderate", temp_min=15, temp_max=30, rainfall_mm=1000,
        days=365, yield_q=80, msp=0, input_cost=80000, profit=400000,
        export="High", demand="Very High", volatility="High", support="Low",
        agro_zones=["himalayan", "coastal", "peninsular"],
        states=["Kerala", "Karnataka", "Tamil Nadu", "Sikkim", "Mizoram", "Maharashtra"],
    ),

    # ═══════════════════════════════════════════════
    # FLOWERS
    # ═══════════════════════════════════════════════
    "marigold": _crop(
        name_hindi="गेंदा", season="year_round", category="Flower",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=15, temp_max=35, rainfall_mm=600,
        days=75, yield_q=120, msp=0, input_cost=30000, profit=120000,
        export="Medium", demand="Very High", volatility="Medium", support="Low",
        agro_zones=["indo_gangetic", "peninsular", "central"],
        states=["Karnataka", "Tamil Nadu", "Andhra Pradesh", "Maharashtra", "Uttar Pradesh"],
    ),
    "rose": _crop(
        name_hindi="गुलाब", season="year_round", category="Flower",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=12, temp_max=30, rainfall_mm=700,
        days=365, yield_q=200, msp=0, input_cost=80000, profit=320000,
        export="High", demand="Very High", volatility="Medium", support="Low",
        agro_zones=["peninsular", "northwest", "himalayan"],
        states=["Karnataka", "Tamil Nadu", "Punjab", "Haryana", "Maharashtra", "Rajasthan"],
    ),
    "chrysanthemum": _crop(
        name_hindi="गुलदाउदी", season="rabi", category="Flower",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=10, temp_max=25, rainfall_mm=600,
        days=100, yield_q=150, msp=0, input_cost=45000, profit=180000,
        export="Medium", demand="High", volatility="Medium", support="Low",
        agro_zones=["peninsular", "indo_gangetic", "himalayan"],
        states=["Karnataka", "Tamil Nadu", "Maharashtra", "Uttar Pradesh", "West Bengal"],
    ),
    "jasmine": _crop(
        name_hindi="चमेली", season="year_round", category="Flower",
        soils=RED + SANDY_LOAM,
        water="Moderate", temp_min=18, temp_max=38, rainfall_mm=600,
        days=365, yield_q=40, msp=0, input_cost=40000, profit=200000,
        export="High", demand="Very High", volatility="Medium", support="Low",
        agro_zones=["peninsular", "coastal", "deccan"],
        states=["Tamil Nadu", "Karnataka", "Andhra Pradesh", "Maharashtra", "Kerala"],
    ),
    "tuberose": _crop(
        name_hindi="रजनीगंधा", season="year_round", category="Flower",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=20, temp_max=35, rainfall_mm=600,
        days=120, yield_q=60, msp=0, input_cost=35000, profit=165000,
        export="Medium", demand="High", volatility="Medium", support="Low",
        agro_zones=["peninsular", "coastal", "indo_gangetic"],
        states=["West Bengal", "Karnataka", "Tamil Nadu", "Andhra Pradesh", "Maharashtra"],
    ),
    "gerbera": _crop(
        name_hindi="जर्बेरा", season="year_round", category="Flower",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=12, temp_max=28, rainfall_mm=700,
        days=365, yield_q=300, msp=0, input_cost=150000, profit=600000,
        export="Very High", demand="Very High", volatility="Medium", support="NHM",
        agro_zones=["himalayan", "peninsular", "northwest"],
        states=["Karnataka", "Maharashtra", "Himachal Pradesh", "West Bengal", "Tamil Nadu"],
    ),

    # ═══════════════════════════════════════════════
    # FODDER
    # ═══════════════════════════════════════════════
    "berseem": _crop(
        name_hindi="बरसीम", season="rabi", category="Fodder",
        soils=ALLUVIAL + CLAY,
        water="High", temp_min=5, temp_max=22, rainfall_mm=500,
        days=150, yield_q=600, msp=0, input_cost=10000, profit=30000,
        export="Low", demand="High", volatility="Low", support="Low",
        agro_zones=["indo_gangetic", "northwest", "himalayan"],
        states=["Punjab", "Haryana", "Uttar Pradesh", "Bihar", "Rajasthan"],
    ),
    "lucerne": _crop(
        name_hindi="लूसर्न", season="year_round", category="Fodder",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=10, temp_max=28, rainfall_mm=500,
        days=365, yield_q=800, msp=0, input_cost=12000, profit=38000,
        export="Low", demand="High", volatility="Low", support="Low",
        agro_zones=["northwest", "indo_gangetic", "deccan"],
        states=["Punjab", "Haryana", "Rajasthan", "Gujarat", "Maharashtra"],
    ),
    "napier_grass": _crop(
        name_hindi="नेपियर घास", season="year_round", category="Fodder",
        soils=ALL_SOILS,
        water="Moderate", temp_min=18, temp_max=40, rainfall_mm=700,
        days=365, yield_q=1200, msp=0, input_cost=8000, profit=32000,
        export="Low", demand="High", volatility="Low", support="Low",
        agro_zones=["peninsular", "coastal", "central", "northeast"],
        states=["Karnataka", "Tamil Nadu", "Andhra Pradesh", "Maharashtra", "Kerala"],
    ),
    "sorghum_sudan": _crop(
        name_hindi="सुडान घास", season="kharif", category="Fodder",
        soils=SANDY_LOAM + LOAMY,
        water="Low", temp_min=20, temp_max=40, rainfall_mm=350,
        days=75, yield_q=400, msp=0, input_cost=7000, profit=23000,
        export="Low", demand="Medium", volatility="Low", support="Low",
        agro_zones=["thar_desert", "central", "deccan"],
        states=["Rajasthan", "Madhya Pradesh", "Maharashtra", "Gujarat", "Haryana"],
    ),
    "cowpea_fodder": _crop(
        name_hindi="लोबिया (चारा)", season="kharif", category="Fodder",
        soils=SANDY_LOAM + LOAMY,
        water="Low", temp_min=22, temp_max=38, rainfall_mm=400,
        days=60, yield_q=250, msp=0, input_cost=7000, profit=21000,
        export="Low", demand="Medium", volatility="Low", support="Low",
        agro_zones=["peninsular", "central", "indo_gangetic"],
        states=["Karnataka", "Maharashtra", "Andhra Pradesh", "Uttar Pradesh", "Rajasthan"],
    ),

    # ═══════════════════════════════════════════════
    # MILLETS (additional)
    # ═══════════════════════════════════════════════
    "kodo_millet": _crop(
        name_hindi="कोदो", season="kharif", category="Millet",
        soils=RED + SANDY_LOAM,
        water="Low", temp_min=20, temp_max=35, rainfall_mm=500,
        days=100, yield_q=12, msp=3846, input_cost=7000, profit=39152,
        export="Low", demand="Medium", volatility="Low", support="MSP",
        agro_zones=["central", "peninsular"],
        states=["Madhya Pradesh", "Chhattisgarh", "Odisha", "Maharashtra", "Karnataka"],
    ),
    "little_millet": _crop(
        name_hindi="कुटकी", season="kharif", category="Millet",
        soils=RED + SANDY_LOAM,
        water="Low", temp_min=20, temp_max=35, rainfall_mm=400,
        days=90, yield_q=8, msp=3939, input_cost=5000, profit=26512,
        export="Low", demand="Medium", volatility="Low", support="MSP",
        agro_zones=["central", "peninsular"],
        states=["Madhya Pradesh", "Chhattisgarh", "Odisha", "Gujarat", "Tamil Nadu"],
    ),
    "proso_millet": _crop(
        name_hindi="चेना", season="kharif", category="Millet",
        soils=SANDY + SANDY_LOAM,
        water="Low", temp_min=20, temp_max=38, rainfall_mm=300,
        days=75, yield_q=10, msp=0, input_cost=5000, profit=20000,
        export="Low", demand="Low", volatility="Low", support="Limited",
        agro_zones=["central", "thar_desert", "peninsular"],
        states=["Rajasthan", "Gujarat", "Madhya Pradesh", "Maharashtra", "Karnataka"],
    ),
    "barnyard_millet": _crop(
        name_hindi="सांवा", season="kharif", category="Millet",
        soils=SANDY_LOAM + RED,
        water="Low", temp_min=18, temp_max=35, rainfall_mm=500,
        days=85, yield_q=12, msp=0, input_cost=5000, profit=22000,
        export="Low", demand="Medium", volatility="Low", support="Limited",
        agro_zones=["himalayan", "northeast", "central"],
        states=["Uttarakhand", "Uttar Pradesh", "Jharkhand", "Odisha", "West Bengal"],
    ),
    "browntop_millet": _crop(
        name_hindi="ब्राउनटॉप मिलेट", season="kharif", category="Millet",
        soils=RED + SANDY_LOAM,
        water="Low", temp_min=20, temp_max=35, rainfall_mm=450,
        days=65, yield_q=10, msp=0, input_cost=4000, profit=18000,
        export="Medium", demand="Medium", volatility="Low", support="Limited",
        agro_zones=["peninsular", "central"],
        states=["Karnataka", "Andhra Pradesh", "Telangana"],
    ),

    # ═══════════════════════════════════════════════
    # MEDICINAL / AROMATIC
    # ═══════════════════════════════════════════════
    "brahmi": _crop(
        name_hindi="ब्राह्मी", season="year_round", category="Medicinal",
        soils=ALLUVIAL + LOAMY,
        water="High", temp_min=18, temp_max=38, rainfall_mm=1000,
        days=120, yield_q=25, msp=0, input_cost=20000, profit=80000,
        export="Medium", demand="High", volatility="Medium", support="AYUSH",
        agro_zones=["coastal", "peninsular", "indo_gangetic"],
        states=["Kerala", "Karnataka", "Andhra Pradesh", "Uttar Pradesh", "Bihar"],
    ),
    "shatavari": _crop(
        name_hindi="शतावरी", season="year_round", category="Medicinal",
        soils=SANDY_LOAM + RED,
        water="Low", temp_min=20, temp_max=40, rainfall_mm=500,
        days=540, yield_q=15, msp=0, input_cost=40000, profit=200000,
        export="High", demand="Very High", volatility="Medium", support="AYUSH",
        agro_zones=["central", "peninsular", "thar_desert"],
        states=["Rajasthan", "Madhya Pradesh", "Gujarat", "Maharashtra", "Uttar Pradesh"],
    ),
    "kalmegh": _crop(
        name_hindi="कालमेघ", season="kharif", category="Medicinal",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=20, temp_max=35, rainfall_mm=700,
        days=120, yield_q=20, msp=0, input_cost=18000, profit=80000,
        export="Medium", demand="High", volatility="Medium", support="AYUSH",
        agro_zones=["peninsular", "coastal", "northeast"],
        states=["West Bengal", "Assam", "Odisha", "Gujarat", "Maharashtra"],
    ),
    "safed_musli": _crop(
        name_hindi="सफेद मूसली", season="kharif", category="Medicinal",
        soils=SANDY_LOAM + LOAMY,
        water="Moderate", temp_min=22, temp_max=38, rainfall_mm=700,
        days=150, yield_q=8, msp=0, input_cost=60000, profit=300000,
        export="Very High", demand="Very High", volatility="High", support="AYUSH",
        agro_zones=["central", "peninsular", "gujarat"],
        states=["Madhya Pradesh", "Rajasthan", "Gujarat", "Chhattisgarh", "Maharashtra"],
    ),
    "tulsi": _crop(
        name_hindi="तुलसी", season="kharif", category="Medicinal",
        soils=LOAMY + SANDY_LOAM,
        water="Low", temp_min=20, temp_max=40, rainfall_mm=500,
        days=120, yield_q=20, msp=0, input_cost=10000, profit=60000,
        export="High", demand="Very High", volatility="Low", support="AYUSH",
        agro_zones=["indo_gangetic", "peninsular", "central"],
        states=["Uttar Pradesh", "Madhya Pradesh", "Rajasthan", "Maharashtra", "Gujarat"],
    ),
    "neem_commercial": _crop(
        name_hindi="नीम (व्यावसायिक)", season="year_round", category="Medicinal",
        soils=ALL_SOILS,
        water="Low", temp_min=18, temp_max=44, rainfall_mm=300,
        days=365, yield_q=30, msp=0, input_cost=20000, profit=100000,
        export="High", demand="High", volatility="Low", support="Low",
        agro_zones=["thar_desert", "central", "peninsular", "deccan"],
        states=["Rajasthan", "Uttar Pradesh", "Madhya Pradesh", "Gujarat", "Maharashtra"],
    ),

    # ═══════════════════════════════════════════════
    # FIBER (additional)
    # ═══════════════════════════════════════════════
    "hemp": _crop(
        name_hindi="भांग / औद्योगिक हेम्प", season="rabi", category="Fiber",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=10, temp_max=26, rainfall_mm=600,
        days=100, yield_q=10, msp=0, input_cost=30000, profit=100000,
        export="High", demand="High", volatility="High", support="State Licence",
        agro_zones=["himalayan", "northwest"],
        states=["Uttarakhand", "Himachal Pradesh", "Jammu and Kashmir"],
    ),
    "ramie": _crop(
        name_hindi="रेमी", season="year_round", category="Fiber",
        soils=LOAMY + ALLUVIAL,
        water="High", temp_min=20, temp_max=35, rainfall_mm=1200,
        days=180, yield_q=25, msp=0, input_cost=25000, profit=75000,
        export="Medium", demand="Low", volatility="Medium", support="Low",
        agro_zones=["northeast", "coastal"],
        states=["Assam", "West Bengal", "Meghalaya", "Odisha"],
    ),
    "sisal": _crop(
        name_hindi="सिसल", season="year_round", category="Fiber",
        soils=SANDY + RED + SANDY_LOAM,
        water="Low", temp_min=20, temp_max=38, rainfall_mm=400,
        days=365, yield_q=20, msp=0, input_cost=18000, profit=50000,
        export="High", demand="Medium", volatility="Low", support="Low",
        agro_zones=["thar_desert", "peninsular", "deccan"],
        states=["Gujarat", "Rajasthan", "Tamil Nadu", "Karnataka"],
    ),

    # ═══════════════════════════════════════════════
    # OILSEEDS (additional)
    # ═══════════════════════════════════════════════
    "niger": _crop(
        name_hindi="रामतिल", season="kharif", category="Oilseed",
        soils=RED + SANDY_LOAM,
        water="Low", temp_min=18, temp_max=35, rainfall_mm=700,
        days=100, yield_q=6, msp=7734, input_cost=10000, profit=36404,
        export="Medium", demand="Medium", volatility="Medium", support="MSP",
        agro_zones=["central", "peninsular"],
        states=["Madhya Pradesh", "Chhattisgarh", "Odisha", "Gujarat", "Maharashtra"],
    ),
    "karanja": _crop(
        name_hindi="करंज", season="year_round", category="Oilseed",
        soils=ALL_SOILS,
        water="Low", temp_min=18, temp_max=45, rainfall_mm=400,
        days=365, yield_q=8, msp=0, input_cost=10000, profit=40000,
        export="Medium", demand="Medium", volatility="Low", support="MNRE",
        agro_zones=["central", "peninsular", "thar_desert"],
        states=["Maharashtra", "Madhya Pradesh", "Rajasthan", "Gujarat", "Andhra Pradesh"],
    ),
    "jatropha": _crop(
        name_hindi="जट्रोफा", season="year_round", category="Oilseed",
        soils=SANDY + SANDY_LOAM + RED,
        water="Low", temp_min=20, temp_max=42, rainfall_mm=300,
        days=365, yield_q=4, msp=0, input_cost=12000, profit=28000,
        export="Low", demand="Low", volatility="Medium", support="MNRE",
        agro_zones=["thar_desert", "central", "peninsular"],
        states=["Rajasthan", "Gujarat", "Madhya Pradesh", "Chhattisgarh", "Andhra Pradesh"],
    ),

    # ═══════════════════════════════════════════════
    # SPICES (additional)
    # ═══════════════════════════════════════════════
    "clove": _crop(
        name_hindi="लौंग", season="year_round", category="Spice",
        soils=RED + LOAMY,
        water="High", temp_min=20, temp_max=30, rainfall_mm=1500,
        days=365, yield_q=3, msp=0, input_cost=80000, profit=400000,
        export="Very High", demand="Very High", volatility="High", support="Spice Board",
        agro_zones=["coastal", "peninsular"],
        states=["Kerala", "Tamil Nadu", "Karnataka"],
    ),
    "nutmeg": _crop(
        name_hindi="जायफल", season="year_round", category="Spice",
        soils=RED + LOAMY,
        water="High", temp_min=20, temp_max=35, rainfall_mm=1500,
        days=365, yield_q=2, msp=0, input_cost=60000, profit=280000,
        export="Very High", demand="High", volatility="High", support="Spice Board",
        agro_zones=["coastal", "peninsular"],
        states=["Kerala", "Tamil Nadu", "Goa"],
    ),
    "star_anise": _crop(
        name_hindi="चक्र फूल", season="year_round", category="Spice",
        soils=LOAMY + RED,
        water="Moderate", temp_min=18, temp_max=30, rainfall_mm=1200,
        days=365, yield_q=4, msp=0, input_cost=40000, profit=200000,
        export="High", demand="High", volatility="Medium", support="Spice Board",
        agro_zones=["northeast", "himalayan"],
        states=["Arunachal Pradesh", "Manipur", "Sikkim"],
    ),
    "fenugreek": _crop(
        name_hindi="मेथी", season="rabi", category="Spice",
        soils=SANDY_LOAM + LOAMY,
        water="Low", temp_min=10, temp_max=25, rainfall_mm=350,
        days=90, yield_q=12, msp=0, input_cost=10000, profit=44000,
        export="High", demand="High", volatility="Medium", support="Low",
        agro_zones=["thar_desert", "northwest", "indo_gangetic"],
        states=["Rajasthan", "Gujarat", "Madhya Pradesh", "Uttar Pradesh", "Haryana"],
    ),
    "ajwain": _crop(
        name_hindi="अजवायन", season="rabi", category="Spice",
        soils=SANDY_LOAM + LOAMY,
        water="Low", temp_min=10, temp_max=26, rainfall_mm=300,
        days=110, yield_q=8, msp=0, input_cost=9000, profit=56000,
        export="High", demand="High", volatility="Medium", support="Low",
        agro_zones=["thar_desert", "northwest", "gujarat"],
        states=["Rajasthan", "Gujarat", "Madhya Pradesh", "Uttar Pradesh"],
    ),

    # ═══════════════════════════════════════════════
    # PULSES (additional)
    # ═══════════════════════════════════════════════
    "horse_gram": _crop(
        name_hindi="कुल्थी", season="kharif", category="Pulse",
        soils=RED + SANDY_LOAM,
        water="Low", temp_min=20, temp_max=38, rainfall_mm=500,
        days=90, yield_q=8, msp=0, input_cost=6000, profit=24000,
        export="Medium", demand="Medium", volatility="Low", support="Low",
        agro_zones=["peninsular", "central", "himalayan"],
        states=["Karnataka", "Andhra Pradesh", "Tamil Nadu", "Madhya Pradesh", "Jharkhand"],
    ),
    "moth_bean": _crop(
        name_hindi="मोठ", season="kharif", category="Pulse",
        soils=SANDY + SANDY_LOAM,
        water="Low", temp_min=24, temp_max=42, rainfall_mm=200,
        days=75, yield_q=6, msp=8685, input_cost=5000, profit=47110,
        export="Medium", demand="Medium", volatility="Low", support="MSP",
        agro_zones=["thar_desert", "northwest"],
        states=["Rajasthan", "Gujarat", "Haryana", "Uttar Pradesh"],
    ),
    "field_pea": _crop(
        name_hindi="मटर (देसी)", season="rabi", category="Pulse",
        soils=LOAMY + ALLUVIAL,
        water="Low", temp_min=7, temp_max=20, rainfall_mm=400,
        days=90, yield_q=12, msp=0, input_cost=10000, profit=30000,
        export="Medium", demand="Medium", volatility="Low", support="Limited",
        agro_zones=["indo_gangetic", "himalayan", "northwest"],
        states=["Uttar Pradesh", "Madhya Pradesh", "Bihar", "Uttarakhand", "Punjab"],
    ),

    # ═══════════════════════════════════════════════
    # VEGETABLES (additional)
    # ═══════════════════════════════════════════════
    "sponge_gourd": _crop(
        name_hindi="तरोई", season="kharif", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=20, temp_max=38, rainfall_mm=600,
        days=65, yield_q=130, msp=0, input_cost=14000, profit=48000,
        export="Low", demand="Medium", volatility="Medium", support="Low",
        agro_zones=["peninsular", "indo_gangetic", "northeast"],
        states=["Maharashtra", "Bihar", "West Bengal", "Uttar Pradesh", "Odisha"],
    ),
    "ash_gourd": _crop(
        name_hindi="पेठा", season="kharif", category="Vegetable",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=20, temp_max=38, rainfall_mm=600,
        days=80, yield_q=250, msp=0, input_cost=16000, profit=59000,
        export="Low", demand="Medium", volatility="Medium", support="Low",
        agro_zones=["peninsular", "indo_gangetic", "central"],
        states=["Uttar Pradesh", "Maharashtra", "Karnataka", "Andhra Pradesh", "Bihar"],
    ),
    "pointed_gourd": _crop(
        name_hindi="परवल", season="kharif", category="Vegetable",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=22, temp_max=38, rainfall_mm=700,
        days=120, yield_q=100, msp=0, input_cost=18000, profit=62000,
        export="Low", demand="High", volatility="Medium", support="Low",
        agro_zones=["indo_gangetic", "central"],
        states=["Uttar Pradesh", "Bihar", "West Bengal", "Odisha", "Madhya Pradesh"],
    ),
    "colocasia": _crop(
        name_hindi="अरबी", season="kharif", category="Vegetable",
        soils=CLAY + ALLUVIAL,
        water="High", temp_min=20, temp_max=35, rainfall_mm=900,
        days=180, yield_q=150, msp=0, input_cost=20000, profit=60000,
        export="Low", demand="Medium", volatility="Medium", support="Low",
        agro_zones=["coastal", "peninsular", "northeast"],
        states=["West Bengal", "Kerala", "Andhra Pradesh", "Maharashtra", "Odisha"],
    ),

    # ═══════════════════════════════════════════════
    # FRUITS (additional)
    # ═══════════════════════════════════════════════
    "plum": _crop(
        name_hindi="बेर (आलूबुखारा)", season="year_round", category="Fruit",
        soils=LOAMY + SANDY_LOAM,
        water="Moderate", temp_min=5, temp_max=25, rainfall_mm=700,
        days=365, yield_q=50, msp=0, input_cost=40000, profit=150000,
        export="Medium", demand="Medium", volatility="Medium", support="Low",
        agro_zones=["himalayan", "northwest"],
        states=["Himachal Pradesh", "Jammu and Kashmir", "Uttarakhand", "Punjab"],
    ),
    "apricot": _crop(
        name_hindi="खुबानी", season="year_round", category="Fruit",
        soils=SANDY_LOAM + LOAMY,
        water="Low", temp_min=2, temp_max=22, rainfall_mm=500,
        days=365, yield_q=30, msp=0, input_cost=35000, profit=120000,
        export="Medium", demand="High", volatility="Medium", support="Low",
        agro_zones=["himalayan"],
        states=["Jammu and Kashmir", "Ladakh", "Himachal Pradesh", "Uttarakhand"],
    ),
    "persimmon": _crop(
        name_hindi="तेंदू / जापानी फल", season="year_round", category="Fruit",
        soils=LOAMY + ALLUVIAL,
        water="Moderate", temp_min=5, temp_max=25, rainfall_mm=800,
        days=365, yield_q=30, msp=0, input_cost=30000, profit=100000,
        export="Low", demand="Low", volatility="Medium", support="Low",
        agro_zones=["himalayan", "northwest"],
        states=["Himachal Pradesh", "Jammu and Kashmir", "Uttarakhand"],
    ),

    # ═══════════════════════════════════════════════
    # OILSEED / PLANTATION (additional)
    # ═══════════════════════════════════════════════
    "safflower": _crop(
        name_hindi="कुसुम", season="rabi", category="Oilseed",
        soils=BLACK + SANDY_LOAM,
        water="Low", temp_min=10, temp_max=28, rainfall_mm=350,
        days=150, yield_q=10, msp=5800, input_cost=14000, profit=44000,
        export="Medium", demand="Medium", volatility="Medium", support="MSP",
        agro_zones=["deccan", "central", "peninsular"],
        states=["Maharashtra", "Karnataka", "Andhra Pradesh", "Madhya Pradesh", "Telangana"],
    ),
    "cocoa": _crop(
        name_hindi="कोको", season="year_round", category="Plantation",
        soils=LOAMY + RED,
        water="High", temp_min=22, temp_max=32, rainfall_mm=1500,
        days=365, yield_q=10, msp=0, input_cost=80000, profit=220000,
        export="High", demand="High", volatility="Medium", support="Cocoa Board",
        agro_zones=["coastal", "peninsular"],
        states=["Kerala", "Karnataka", "Andhra Pradesh", "Tamil Nadu"],
    ),
}
