# Generated by Django 4.2.28 on 2026-06-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0004_diagnosticsession_expertverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(db_index=True, help_text="Farmer's field identifier", max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('nitrogen_kg_ha', models.FloatField(blank=True, null=True)),
                ('phosphorus_kg_ha', models.FloatField(blank=True, null=True)),
                ('potassium_kg_ha', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('ec_ds_m', models.FloatField(blank=True, help_text='Electrical Conductivity dS/m', null=True)),
                ('organic_carbon', models.FloatField(blank=True, help_text='OC %', null=True)),
                ('sulfur_ppm', models.FloatField(blank=True, null=True)),
                ('zinc_ppm', models.FloatField(blank=True, null=True)),
                ('moisture_pct', models.FloatField(blank=True, help_text='Volumetric moisture %', null=True)),
                ('soil_temp_c', models.FloatField(blank=True, null=True)),
                ('bulk_density', models.FloatField(blank=True, null=True)),
                ('sensor_device_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'iot_sensor_readings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['field_id', 'created_at'], name='iot_sensor__field_i_a0bd09_idx'), models.Index(fields=['latitude', 'longitude'], name='iot_sensor__latitud_53c42f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldSoilHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_grid', models.FloatField(db_index=True, help_text='latitude rounded to 3dp')),
                ('lon_grid', models.FloatField(db_index=True, help_text='longitude rounded to 3dp')),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('avg_nitrogen', models.FloatField(blank=True, null=True)),
                ('avg_phosphorus', models.FloatField(blank=True, null=True)),
                ('avg_potassium', models.FloatField(blank=True, null=True)),
                ('avg_ph', models.FloatField(blank=True, null=True)),
                ('avg_oc', models.FloatField(blank=True, null=True)),
                ('avg_ec', models.FloatField(blank=True, null=True)),
                ('reading_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_source', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'field_soil_history',
                'unique_together': {('lat_grid', 'lon_grid')},
            },
        ),
    ]
