# Generated by Django 4.2.28 on 2026-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0007_farmer_profile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='farmerprofile',
            new_name='farmer_prof_phone_n_314000_idx',
            old_name='farmer_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='farmerprofile',
            new_name='farmer_prof_session_9948e4_idx',
            old_name='farmer_session_idx',
        ),
        migrations.RenameIndex(
            model_name='farmerprofile',
            new_name='farmer_prof_state_3959b0_idx',
            old_name='farmer_location_idx',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='msp_per_quintal',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='msp_season',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='name_hindi',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='season',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='detected_language',
            field=models.CharField(blank=True, default='', help_text='Detected language', max_length=10),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='response_language',
            field=models.CharField(blank=True, default='', help_text='Response language', max_length=10),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='response_source',
            field=models.CharField(blank=True, default='', help_text='Source of response (advanced_chatbot, fallback, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='response_type',
            field=models.CharField(blank=True, default='', help_text='Type of response (greeting, agricultural, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='crop_history',
            field=models.JSONField(default=list, help_text='e.g. [{"season":"Rabi 2023-24","crop":"wheat","issue":"aphid"}]'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='current_season',
            field=models.CharField(blank=True, help_text='Kharif 2025 | Rabi 2025-26', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_size_bigha',
            field=models.FloatField(blank=True, help_text='Farm size in bigha', null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_size_hectare',
            field=models.FloatField(blank=True, help_text='Farm size in hectare (1 bigha ≈ 0.2 ha)', null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='irrigation_type',
            field=models.CharField(blank=True, help_text='drip | sprinkler | flood | rainfed', max_length=30),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='pm_kisan_status',
            field=models.CharField(blank=True, help_text='active | pending | none', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Web/app session ID for non-WhatsApp users', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='soil_type',
            field=models.CharField(blank=True, help_text='loamy | clay | sandy | black | red', max_length=50),
        ),
    ]
