# Generated by Django 4.2.28 on 2026-06-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0008_chathistory_field_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='msp_per_quintal',
            field=models.PositiveIntegerField(default=0, help_text='Minimum Support Price ₹/quintal (0 = no government MSP). Update annually after CACP Cabinet approval.'),
        ),
        migrations.AddField(
            model_name='crop',
            name='msp_season',
            field=models.CharField(blank=True, default='', help_text="Season the MSP applies to e.g. '2024-25'", max_length=10),
        ),
        migrations.AddField(
            model_name='crop',
            name='name_hindi',
            field=models.CharField(blank=True, default='', help_text='Crop name in Hindi script', max_length=100),
        ),
        migrations.AddField(
            model_name='crop',
            name='season',
            field=models.CharField(blank=True, default='', help_text='rabi | kharif | zaid | year_round', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['session_id'], name='chat_histor_session_37a41e_idx'),
        ),
    ]
