# Generated by Django 4.2.28 on 2026-07-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0011_iotsensorreading_latlon_created_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='ai_tier',
            field=models.CharField(blank=True, help_text='gemini | qwen_rag | rule_based', max_length=30),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='crops_detected',
            field=models.JSONField(default=list, help_text='Crop names extracted from the query'),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='feedback_score',
            field=models.IntegerField(blank=True, help_text='1-5 farmer satisfaction rating (from feedback button)', null=True),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='feedback_text',
            field=models.TextField(blank=True, help_text='Optional feedback text'),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='intent',
            field=models.CharField(blank=True, help_text='Classified intent: irrigation, pest_disease, market_price, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='is_helpful',
            field=models.BooleanField(blank=True, help_text='True/False from thumbs up/down', null=True),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='market_prices',
            field=models.JSONField(blank=True, help_text='Top crop prices at time of query for market-related queries', null=True),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='query',
            field=models.TextField(help_text="Farmer's question"),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='response',
            field=models.TextField(help_text='AI response text'),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='response_time_ms',
            field=models.IntegerField(blank=True, help_text='AI response generation time in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='sensor_data',
            field=models.JSONField(blank=True, help_text='IoT sensor readings: moisture, NPK, pH at time of query', null=True),
        ),
        migrations.AlterField(
            model_name='farmerinteractionlog',
            name='weather_data',
            field=models.JSONField(blank=True, help_text='Weather conditions: temp, humidity, alerts at time of query', null=True),
        ),
        migrations.CreateModel(
            name='CropRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('agro_zone', models.CharField(blank=True, max_length=50)),
                ('season', models.CharField(blank=True, db_index=True, max_length=20)),
                ('recommendations', models.JSONField(help_text='List of {crop_key, crop_name, score, rank} dicts')),
                ('top_crop', models.CharField(blank=True, db_index=True, max_length=100)),
                ('profile_source', models.CharField(blank=True, help_text='district_exact | state_first_district | keyword | gps_zone', max_length=50)),
                ('soil_type', models.CharField(blank=True, max_length=50)),
                ('rainfall_band', models.CharField(blank=True, max_length=20)),
                ('irrigation', models.CharField(blank=True, max_length=20)),
                ('weather_risk', models.CharField(blank=True, max_length=50)),
                ('current_temp', models.FloatField(blank=True, null=True)),
                ('market_is_live', models.BooleanField(default=False)),
                ('farmer_adopted', models.BooleanField(blank=True, help_text='Did farmer actually grow the recommended crop?', null=True)),
                ('adopted_crop', models.CharField(blank=True, help_text='Which crop they actually grew', max_length=100)),
                ('outcome_rating', models.IntegerField(blank=True, help_text='1-5: how well the recommendation worked out', null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='hi', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'crop_recommendation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='crop_recomm_session_c7e5b1_idx'), models.Index(fields=['state', 'season', 'created_at'], name='crop_recomm_state_f7cf39_idx'), models.Index(fields=['top_crop', 'state'], name='crop_recomm_top_cro_2c7653_idx'), models.Index(fields=['agro_zone', 'season'], name='crop_recomm_agro_zo_0185d5_idx'), models.Index(fields=['farmer_adopted', 'top_crop'], name='crop_recomm_farmer__fdf97b_idx')],
            },
        ),
    ]
